all:
  hosts:
    proxmox:
      ansible_host: 192.168.1.227        # IP statico Proxmox
      ansible_user: root                 # user abilitato SSH
      ansible_ssh_private_key_file: ~/.ssh/r3dpanth3rlab_root
